package local.spring.model;
// Generated 03/07/2017 01:54:50 AM by Hibernate Tools 4.3.1



/**
 * Detalle generated by hbm2java
 */
public class Detalle  implements java.io.Serializable {


     private int iddetalle;
     private Venta venta;
     private int cantidad;
     private int precioFinal;

    public Detalle() {
    }

    public Detalle(Venta venta, int cantidad, int precioFinal) {
       this.venta = venta;
       this.cantidad = cantidad;
       this.precioFinal = precioFinal;
    }
   
    public int getIddetalle() {
        return this.iddetalle;
    }
    
    public void setIddetalle(int iddetalle) {
        this.iddetalle = iddetalle;
    }
    public Venta getVenta() {
        return this.venta;
    }
    
    public void setVenta(Venta venta) {
        this.venta = venta;
    }
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }
    public int getPrecioFinal() {
        return this.precioFinal;
    }
    
    public void setPrecioFinal(int precioFinal) {
        this.precioFinal = precioFinal;
    }




}


