package local.spring.model;
// Generated 03/07/2017 01:54:50 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Persona generated by hbm2java
 */
public class Persona  implements java.io.Serializable {


     private int idpersona;
     private String nombre;
     private String apellido;
     private Date fechaN;
     private boolean genero;
     private String email;
     private String direccion;
     private String telefono;
     private String pais;
     private Usuario usuario;

    public Persona() {
    }

	
    public Persona(int idpersona, String nombre, String apellido, Date fechaN, boolean genero, String email, String telefono) {
        this.idpersona = idpersona;
        this.nombre = nombre;
        this.apellido = apellido;
        this.fechaN = fechaN;
        this.genero = genero;
        this.email = email;
        this.telefono = telefono;
    }
    public Persona(int idpersona, String nombre, String apellido, Date fechaN, boolean genero, String email, String direccion, String telefono, String pais, Usuario usuario) {
       this.idpersona = idpersona;
       this.nombre = nombre;
       this.apellido = apellido;
       this.fechaN = fechaN;
       this.genero = genero;
       this.email = email;
       this.direccion = direccion;
       this.telefono = telefono;
       this.pais = pais;
       this.usuario = usuario;
    }
   
    public int getIdpersona() {
        return this.idpersona;
    }
    
    public void setIdpersona(int idpersona) {
        this.idpersona = idpersona;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public Date getFechaN() {
        return this.fechaN;
    }
    
    public void setFechaN(Date fechaN) {
        this.fechaN = fechaN;
    }
    public boolean isGenero() {
        return this.genero;
    }
    
    public void setGenero(boolean genero) {
        this.genero = genero;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getPais() {
        return this.pais;
    }
    
    public void setPais(String pais) {
        this.pais = pais;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }




}


