package local.spring.model;
// Generated 03/07/2017 01:54:50 AM by Hibernate Tools 4.3.1



/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private int idusuario;
     private Persona persona;
     private Rol rol;
     private String user;
     private String pass;
     private Integer estado;
     private Integer contador;
     private Venta venta;

    public Usuario() {
    }

	
    public Usuario(Persona persona, Rol rol, String user, String pass) {
        this.persona = persona;
        this.rol = rol;
        this.user = user;
        this.pass = pass;
    }
    public Usuario(Persona persona, Rol rol, String user, String pass, Integer estado, Integer contador, Venta venta) {
       this.persona = persona;
       this.rol = rol;
       this.user = user;
       this.pass = pass;
       this.estado = estado;
       this.contador = contador;
       this.venta = venta;
    }
   
    public int getIdusuario() {
        return this.idusuario;
    }
    
    public void setIdusuario(int idusuario) {
        this.idusuario = idusuario;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public Rol getRol() {
        return this.rol;
    }
    
    public void setRol(Rol rol) {
        this.rol = rol;
    }
    public String getUser() {
        return this.user;
    }
    
    public void setUser(String user) {
        this.user = user;
    }
    public String getPass() {
        return this.pass;
    }
    
    public void setPass(String pass) {
        this.pass = pass;
    }
    public Integer getEstado() {
        return this.estado;
    }
    
    public void setEstado(Integer estado) {
        this.estado = estado;
    }
    public Integer getContador() {
        return this.contador;
    }
    
    public void setContador(Integer contador) {
        this.contador = contador;
    }
    public Venta getVenta() {
        return this.venta;
    }
    
    public void setVenta(Venta venta) {
        this.venta = venta;
    }




}


